name: Push package to Azure Artifacts

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 16

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Run build
      - name: npm install, build package
        run: |
          npm install
          npm run dist

  az-artifacts-build-and-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      # set auth conf in .npmrc
      - run: cat .npmrc | sed 's/{AZURE_DEVOPS_TOKEN}/${{ secrets.AZURE_DEVOPS_TOKEN }}/' | sed 's/{username}/${{ vars.AZURE_USERNAME }}/' | sed 's/{email}/${{ vars.AZURE_EMAIL }}/' > .npmrc

      - name: Get version of the project
        id: project-version
        uses: 'euberdeveloper/ga-project-version@main'

      - name: Clean and set package version
        run: |
          npm ci
          git add .
          git config --global user.email "my-user@me.com"
          git config --global user.name "my-user"
          git commit -m 'commit to change version'
          npm version ${{ steps.project-version.outputs.version }}-v-${{ github.run_number  }}


      # Publish
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}